// ══ ONCLICK -> ADDEVENTLISTENER WIRING (static markup only) ══
// Generated by converting onclick="EXPR" attributes on fixed markup
// elements into addEventListener calls. An inline onclick="EXPR" is
// exactly equivalent to el.addEventListener('click', function(event){
// EXPR }) -- both bind `this` to the element and expose `event` in
// scope -- so this preserves behavior exactly rather than changing it.
//
// Scope: only elements present in the initial HTML. Elements rendered
// dynamically via template literals (menu items, coupons, stock rows,
// etc.) still use inline onclick -- converting those requires rewriting
// each render function to use event delegation instead, which is a
// separate, larger change.
document.getElementById('oc-cust-1').addEventListener('click', function(event){ enterApp() });
document.getElementById('oc-cust-2').addEventListener('click', function(event){ openStoreSelector() });
document.getElementById('oc-cust-3').addEventListener('click', function(event){ setMode('pickup',this) });
document.getElementById('oc-cust-4').addEventListener('click', function(event){ showToast('Delivery coming soon','🚧') });
document.getElementById('home-hero').addEventListener('click', function(event){ goPage('pg-menu') });
document.getElementById('oc-cust-6').addEventListener('click', function(event){ goPage('pg-menu') });
document.getElementById('oc-cust-7').addEventListener('click', function(event){ modePick(this,'pickup') });
document.getElementById('oc-cust-8').addEventListener('click', function(event){ showToast('Delivery coming soon','🚧') });
document.getElementById('oc-cust-9').addEventListener('click', function(event){ openStoreSelector() });
document.getElementById('oc-cust-10').addEventListener('click', function(event){ openCartReview() });
document.getElementById('oc-cust-11').addEventListener('click', function(event){ openCheckout() });
document.getElementById('oc-cust-12').addEventListener('click', function(event){ openCartReview() });
document.getElementById('oc-cust-13').addEventListener('click', function(event){ openCheckout() });
document.getElementById('oc-cust-14').addEventListener('click', function(event){ switchOrderTab(0,this) });
document.getElementById('oc-cust-15').addEventListener('click', function(event){ switchOrderTab(1,this) });
document.getElementById('oc-cust-16').addEventListener('click', function(event){ switchOrderTab(2,this) });
document.getElementById('oc-cust-17').addEventListener('click', function(event){ openSettingsModal() });
document.getElementById('oc-cust-18').addEventListener('click', function(event){ openFavouritesModal() });
document.getElementById('oc-cust-19').addEventListener('click', function(event){ showToast('Use the coupon field at checkout','🎟️') });
document.getElementById('oc-cust-20').addEventListener('click', function(event){ openAddressManagerModal() });
document.getElementById('oc-cust-21').addEventListener('click', function(event){ showToast('We read every message','💬') });
document.getElementById('oc-cust-22').addEventListener('click', function(event){ closeModal('modal-settings') });
document.getElementById('settings-save-btn').addEventListener('click', function(event){ saveSettings() });
document.getElementById('oc-cust-24').addEventListener('click', function(event){ closeModal('modal-favourites') });
document.getElementById('oc-cust-25').addEventListener('click', function(event){ closeModal('modal-address-manager') });
document.getElementById('oc-cust-26').addEventListener('click', function(event){ openAddAddressForm() });
document.getElementById('oc-cust-27').addEventListener('click', function(event){ closeModal('modal-address-form') });
document.getElementById('address-save-btn').addEventListener('click', function(event){ saveAddress() });
document.getElementById('bnav-home').addEventListener('click', function(event){ goPage('pg-home',this) });
document.getElementById('bnav-menu').addEventListener('click', function(event){ goPage('pg-menu',this) });
document.getElementById('bnav-center').addEventListener('click', function(event){ goPage('pg-order',this) });
document.getElementById('bnav-orders').addEventListener('click', function(event){ goPage('pg-orders',this) });
document.getElementById('bnav-profile').addEventListener('click', function(event){ goPage('pg-profile',this) });
document.getElementById('oc-cust-34').addEventListener('click', function(event){ closeModal('modal-cart-review') });
document.getElementById('oc-cust-35').addEventListener('click', function(event){ closeModal('modal-cart-review');openCheckout() });
document.getElementById('oc-cust-36').addEventListener('click', function(event){ closeModal('modal-item') });
document.getElementById('modal-item-fav-btn').addEventListener('click', function(event){ toggleFavourite(currentItem?.id, false) });
document.getElementById('oc-cust-38').addEventListener('click', function(event){ changeDetailQty(-1) });
document.getElementById('oc-cust-39').addEventListener('click', function(event){ changeDetailQty(1) });
document.getElementById('add-cart-btn').addEventListener('click', function(event){ addToCartFromModal() });
document.getElementById('oc-cust-41').addEventListener('click', function(event){ closeModal('modal-merch-item') });
document.getElementById('modal-merch-fav-btn').addEventListener('click', function(event){ toggleFavourite(currentMerchItem?.id, true) });
document.getElementById('oc-cust-43').addEventListener('click', function(event){ changeMerchDetailQty(-1) });
document.getElementById('oc-cust-44').addEventListener('click', function(event){ changeMerchDetailQty(1) });
document.getElementById('add-merch-cart-btn').addEventListener('click', function(event){ addMerchToCartFromModal() });
document.getElementById('oc-cust-46').addEventListener('click', function(event){ closeModal('modal-store') });
document.getElementById('oc-cust-47').addEventListener('click', function(event){ closeModal('modal-checkout') });
document.getElementById('oc-cust-48').addEventListener('click', function(event){ closeModal('modal-checkout');openStoreSelector() });
document.getElementById('oc-cust-49').addEventListener('click', function(event){ closeModal('modal-checkout');openStoreSelector() });
document.getElementById('oc-cust-50').addEventListener('click', function(event){ closeModal('modal-checkout');openAddressManagerModal() });
document.getElementById('oc-cust-51').addEventListener('click', function(event){ pickPayment(this) });
document.getElementById('oc-cust-52').addEventListener('click', function(event){ pickPayment(this) });
document.getElementById('oc-cust-53').addEventListener('click', function(event){ pickPayment(this) });
document.getElementById('oc-cust-54').addEventListener('click', function(event){ pickPayment(this) });
document.getElementById('oc-cust-55').addEventListener('click', function(event){ applyCoupon() });
document.getElementById('oc-cust-56').addEventListener('click', function(event){ placeOrder() });
document.getElementById('ca-tab-login').addEventListener('click', function(event){ switchCheckoutAuthTab('login') });
document.getElementById('ca-tab-signup').addEventListener('click', function(event){ switchCheckoutAuthTab('signup') });
document.getElementById('ca-login-btn').addEventListener('click', function(event){ doCheckoutLogin() });
document.getElementById('ca-signup-btn').addEventListener('click', function(event){ doCheckoutSignup() });
document.getElementById('oc-cust-61').addEventListener('click', function(event){ closeCheckoutAuthModal() });
