// ══ ONCLICK -> ADDEVENTLISTENER WIRING (static markup only) ══
// Generated by converting onclick="EXPR" attributes on fixed markup
// elements into addEventListener calls. An inline onclick="EXPR" is
// exactly equivalent to el.addEventListener('click', function(event){
// EXPR }) -- both bind `this` to the element and expose `event` in
// scope -- so this preserves behavior exactly rather than changing it.
//
// Scope: only elements present in the initial HTML. Elements rendered
// dynamically via template literals (menu items, coupons, stock rows,
// etc.) still use inline onclick -- converting those requires rewriting
// each render function to use event delegation instead, which is a
// separate, larger change.
document.getElementById('auth-tab-login').addEventListener('click', function(event){ switchAuthTab('login') });
document.getElementById('auth-tab-signup').addEventListener('click', function(event){ switchAuthTab('signup') });
document.getElementById('login-btn').addEventListener('click', function(event){ doLogin() });
document.getElementById('signup-btn').addEventListener('click', function(event){ doSignup() });
document.getElementById('oc-fee-5').addEventListener('click', function(event){ confirmCash() });
document.getElementById('oc-fee-6').addEventListener('click', function(event){ dismissCash() });
document.getElementById('oc-fee-7').addEventListener('click', function(event){ goToOrders() });
document.getElementById('notif-btn').addEventListener('click', function(event){ navigate('alerts') });
document.getElementById('oc-fee-9').addEventListener('click', function(event){ doFranchiseeLogout() });
document.getElementById('oc-fee-10').addEventListener('click', function(event){ navigate('orders') });
document.getElementById('oc-fee-11').addEventListener('click', function(event){ openSaleModal() });
document.getElementById('oc-fee-12').addEventListener('click', function(event){ navigate('stock') });
document.getElementById('oc-fee-13').addEventListener('click', function(event){ navigate('machine') });
document.getElementById('oc-fee-14').addEventListener('click', function(event){ navigate('finance') });
document.getElementById('oc-fee-15').addEventListener('click', function(event){ openIssueModal() });
document.getElementById('oc-fee-16').addEventListener('click', function(event){ filterOrders('all',this) });
document.getElementById('oc-fee-17').addEventListener('click', function(event){ filterOrders('cash',this) });
document.getElementById('oc-fee-18').addEventListener('click', function(event){ filterOrders('new',this) });
document.getElementById('oc-fee-19').addEventListener('click', function(event){ filterOrders('preparing',this) });
document.getElementById('oc-fee-20').addEventListener('click', function(event){ filterOrders('ready',this) });
document.getElementById('oc-fee-21').addEventListener('click', function(event){ filterOrders('done',this) });
document.getElementById('oc-fee-22').addEventListener('click', function(event){ openStockRequestModal() });
document.getElementById('machine-event-submit-btn').addEventListener('click', function(event){ submitMachineEvent() });
document.getElementById('oc-fee-24').addEventListener('click', function(event){ openIssueModal() });
document.getElementById('oc-fee-25').addEventListener('click', function(event){ openIssueModal() });
document.getElementById('oc-fee-26').addEventListener('click', function(event){ openWasteModal() });
document.getElementById('bnav-home').addEventListener('click', function(event){ navigate('home',this) });
document.getElementById('bnav-orders').addEventListener('click', function(event){ navigate('orders',this) });
document.getElementById('bnav-stock').addEventListener('click', function(event){ navigate('stock',this) });
document.getElementById('bnav-machine').addEventListener('click', function(event){ navigate('machine',this) });
document.getElementById('bnav-finance').addEventListener('click', function(event){ navigate('finance',this) });
document.getElementById('bnav-stats').addEventListener('click', function(event){ navigate('stats',this) });
document.getElementById('oc-fee-33').addEventListener('click', function(event){ closeModal('modal-sale') });
document.getElementById('oc-fee-34').addEventListener('click', function(event){ stepQty(-1) });
document.getElementById('oc-fee-35').addEventListener('click', function(event){ stepQty(1) });
document.getElementById('oc-fee-36').addEventListener('click', function(event){ pickMethod(this) });
document.getElementById('oc-fee-37').addEventListener('click', function(event){ pickMethod(this) });
document.getElementById('oc-fee-38').addEventListener('click', function(event){ pickMethod(this) });
document.getElementById('sale-submit-btn').addEventListener('click', function(event){ submitSale() });
document.getElementById('oc-fee-40').addEventListener('click', function(event){ closeModal('modal-waste') });
document.getElementById('waste-submit-btn').addEventListener('click', function(event){ submitWasteLog() });
document.getElementById('oc-fee-42').addEventListener('click', function(event){ closeModal('modal-issue') });
document.getElementById('oc-fee-43').addEventListener('click', function(event){ pickMethod(this) });
document.getElementById('oc-fee-44').addEventListener('click', function(event){ pickMethod(this) });
document.getElementById('oc-fee-45').addEventListener('click', function(event){ pickMethod(this) });
document.getElementById('issue-submit-btn').addEventListener('click', function(event){ submitIssue() });
document.getElementById('oc-fee-47').addEventListener('click', function(event){ closeModal('modal-stock-req') });
document.getElementById('stock-req-submit-btn').addEventListener('click', function(event){ submitStockRequest() });
